//! # nc-codegen — Deterministic Rust Code Generator
//!
//! Transforms validated IR (`ApiEndpoint`) into compilable Rust source code.
//! Every generated fragment comes from a pre-verified template — the generator
//! performs **lookup, not creation**. Same input always produces the same output.
//!
//! ## Why This Guarantees Correctness
//!
//! The IR whitelist (nc-ir) ensures only legal combinations reach this stage.
//! Each IR variant maps to exactly one code template. Templates are hand-written,
//! tested, and frozen. The generator is a pure function: `IR → String`.

use nc_ir::*;

/// Generate a complete, self-contained Rust source file from a list of API endpoints.
///
/// The output includes:
/// - Type stubs for all referenced schema types
/// - Handler functions with correct signatures
/// - An `axum::Router` that wires everything together
/// - A `main()` that starts the server
///
/// The generated code compiles with: `cargo add axum tokio serde --features ...`
pub fn generate(endpoints: &[ApiEndpoint]) -> String {
    let mut out = String::new();

    // -- Header
    out.push_str("// ============================================================\n");
    out.push_str("// AUTO-GENERATED by Neural Codegen (nc-codegen)\n");
    out.push_str("// S-expr DSL → Typed IR → This file. Do not edit manually.\n");
    out.push_str("// ============================================================\n\n");

    // -- Feature flags needed
    let needs_multipart = endpoints.iter().any(|ep| matches!(ep.input, InputSpec::File { .. }));
    let needs_auth = endpoints.iter().any(|ep| ep.auth == AuthRequirement::Required || ep.auth == AuthRequirement::Optional);
    let needs_state = endpoints.iter().any(|ep| !ep.state.is_empty());
    let needs_db = endpoints.iter().any(|ep| ep.state.contains(&StateDep::DbPool));
    let needs_cache = endpoints.iter().any(|ep| ep.state.contains(&StateDep::Cache));

    // -- Imports
    out.push_str("use axum::{\n");
    out.push_str("    Router,\n");
    out.push_str("    routing::{get, post, put, delete},\n");
    out.push_str("    response::IntoResponse,\n");
    out.push_str("    Json,\n");
    out.push_str("};\n");
    if needs_auth {
        out.push_str("use axum::extract::FromRequestParts;\n");
        out.push_str("use axum::http::request::Parts;\n");
    }
    out.push_str("use serde::{Deserialize, Serialize};\n");
    out.push_str("use std::net::SocketAddr;\n");
    if needs_state {
        out.push_str("use std::sync::Arc;\n");
        out.push_str("use tokio::sync::Mutex;\n");
    }
    out.push('\n');

    // -- Dep hint comment
    out.push_str("// Dependencies (Cargo.toml):\n");
    if needs_multipart {
        out.push_str("//   axum = { version = \"0.8\", features = [\"multipart\"] }\n");
    } else {
        out.push_str("//   axum = \"0.8\"\n");
    }
    out.push_str("//   tokio = { version = \"1\", features = [\"full\"] }\n");
    out.push_str("//   serde = { version = \"1\", features = [\"derive\"] }\n\n");

    // -- Collect all unique schema types and generate stubs
    let mut schemas: Vec<String> = Vec::new();
    for ep in endpoints {
        if let InputSpec::Json { schema } = &ep.input {
            if !schemas.contains(schema) { schemas.push(schema.clone()); }
        }
        if let OutputSpec::Json { schema } = &ep.output {
            if !schemas.contains(schema) { schemas.push(schema.clone()); }
        }
    }

    if !schemas.is_empty() {
        out.push_str("// --- Schema types (stubs — implement your fields) ---\n\n");
        for schema in &schemas {
            out.push_str(&format!(
                "#[derive(Debug, Clone, Serialize, Deserialize)]\npub struct {schema} {{\n    // TODO: define fields\n}}\n\n"
            ));
        }
    }

    // -- AppState (if any endpoint uses :state)
    if needs_state {
        out.push_str("// --- Shared application state (auto-generated from :state declarations) ---\n\n");
        out.push_str("#[derive(Clone)]\n");
        out.push_str("pub struct AppState {\n");
        if needs_db {
            out.push_str("    pub db_pool: Arc<Mutex<Vec<String>>>,  // simulated DB connection pool\n");
        }
        if needs_cache {
            out.push_str("    pub cache: Arc<Mutex<std::collections::HashMap<String, String>>>,\n");
        }
        out.push_str("}\n\n");
    }

    // -- Auth extractor (if any endpoint requires auth)
    if needs_auth {
        out.push_str("// --- Auth extractor (pre-verified template) ---\n\n");
        out.push_str("#[derive(Debug, Clone)]\npub struct AuthUser {\n    pub user_id: String,\n}\n\n");
        out.push_str("impl<S: Send + Sync> FromRequestParts<S> for AuthUser {\n");
        out.push_str("    type Rejection = AppError;\n\n");
        out.push_str("    async fn from_request_parts(parts: &mut Parts, _state: &S) -> Result<Self, Self::Rejection> {\n");
        out.push_str("        // Extract user from Authorization header (stub — replace with real logic)\n");
        out.push_str("        let _auth_header = parts.headers.get(\"authorization\")\n");
        out.push_str("            .and_then(|v| v.to_str().ok())\n");
        out.push_str("            .ok_or_else(|| AppError(\"Missing Authorization header\".into()))?;\n");
        out.push_str("        Ok(AuthUser { user_id: \"stub-user\".into() })\n");
        out.push_str("    }\n");
        out.push_str("}\n\n");
    }

    // -- Error type
    out.push_str("// --- Error type ---\n\n");
    out.push_str("#[derive(Debug)]\npub struct AppError(String);\n\n");
    out.push_str("impl IntoResponse for AppError {\n");
    out.push_str("    fn into_response(self) -> axum::response::Response {\n");
    out.push_str("        (axum::http::StatusCode::INTERNAL_SERVER_ERROR, self.0).into_response()\n");
    out.push_str("    }\n}\n\n");

    // -- Handler functions
    out.push_str("// --- Handlers ---\n\n");
    for ep in endpoints {
        out.push_str(&generate_handler(ep, endpoints, needs_state));
        out.push('\n');
    }

    // -- Router
    out.push_str("// --- Router ---\n\n");
    if needs_state {
        out.push_str("pub fn app(state: AppState) -> Router {\n");
    } else {
        out.push_str("pub fn app() -> Router {\n");
    }
    out.push_str("    Router::new()\n");
    for ep in endpoints {
        let fn_name = unique_fn_name(ep, endpoints);
        let method_fn = match ep.method {
            HttpMethod::Get => "get",
            HttpMethod::Post => "post",
            HttpMethod::Put => "put",
            HttpMethod::Delete => "delete",
        };
        out.push_str(&format!("        .route(\"{}\", {method_fn}({fn_name}))\n", ep.path));
    }
    if needs_state {
        out.push_str("        .with_state(state)\n");
    }
    out.push_str("}\n\n");

    // -- Main
    out.push_str("// --- Entry point ---\n\n");
    out.push_str("#[tokio::main]\nasync fn main() {\n");
    if needs_state {
        out.push_str("    let state = AppState {\n");
        if needs_db {
            out.push_str("        db_pool: Arc::new(Mutex::new(Vec::new())),\n");
        }
        if needs_cache {
            out.push_str("        cache: Arc::new(Mutex::new(std::collections::HashMap::new())),\n");
        }
        out.push_str("    };\n");
    }
    out.push_str("    let addr = SocketAddr::from(([127, 0, 0, 1], 3000));\n");
    out.push_str("    println!(\"Listening on {addr}\");\n");
    out.push_str("    let listener = tokio::net::TcpListener::bind(addr).await.unwrap();\n");
    if needs_state {
        out.push_str("    axum::serve(listener, app(state)).await.unwrap();\n");
    } else {
        out.push_str("    axum::serve(listener, app()).await.unwrap();\n");
    }
    out.push_str("}\n");

    out
}

/// Generate a single handler function from an `ApiEndpoint`.
fn generate_handler(ep: &ApiEndpoint, all: &[ApiEndpoint], any_needs_state: bool) -> String {
    let fn_name = unique_fn_name(ep, all);
    let mut params = Vec::new();
    let mut body_lines = Vec::new();

    // Description as doc comment
    if let Some(desc) = &ep.description {
        body_lines.push(format!("/// {desc}"));
    }

    // State extractor — if ANY endpoint uses state, ALL handlers must accept State
    // (axum Router<S> requires all handlers to be Handler<_, S>)
    if any_needs_state {
        if !ep.state.is_empty() {
            params.push("axum::extract::State(state): axum::extract::State<AppState>".to_string());
            for dep in &ep.state {
                match dep {
                    StateDep::DbPool => {
                        body_lines.push("    let _db = state.db_pool.lock().await; // Arc<Mutex<>> auto-managed".into());
                    }
                    StateDep::Cache => {
                        body_lines.push("    let _cache = state.cache.lock().await; // Arc<Mutex<>> auto-managed".into());
                    }
                }
            }
        } else {
            params.push("axum::extract::State(_state): axum::extract::State<AppState>".to_string());
        }
    }

    // Auth parameter
    match ep.auth {
        AuthRequirement::Required => {
            params.push("_auth: AuthUser".to_string());
            body_lines.push("    // Auth: required — AuthUser extractor validates token".into());
        }
        AuthRequirement::Optional => {
            params.push("_auth: Option<AuthUser>".to_string());
            body_lines.push("    // Auth: optional — None if no Authorization header".into());
        }
        AuthRequirement::None => {}
    }

    // Input parameter
    match &ep.input {
        InputSpec::Json { schema } => {
            params.push(format!("Json(payload): Json<{schema}>"));
            body_lines.push(format!("    let _ = payload; // TODO: use {schema} payload"));
        }
        InputSpec::File { max_size, .. } => {
            params.push("mut multipart: axum::extract::Multipart".to_string());
            if let Some(size) = max_size {
                body_lines.push(format!("    // Max upload size: {size}"));
            }
            body_lines.push("    while let Some(_field) = multipart.next_field().await.map_err(|e| AppError(e.to_string()))? {".into());
            body_lines.push("        // TODO: process uploaded file".into());
            body_lines.push("    }".into());
        }
        InputSpec::Query { params: qp } => {
            params.push("axum::extract::Query(query): axum::extract::Query<std::collections::HashMap<String, String>>".to_string());
            for p in qp {
                body_lines.push(format!("    let _{p} = query.get(\"{p}\");"));
            }
        }
        InputSpec::None => {}
    }

    // Rate limit comment
    if let Some(rl) = &ep.rate_limit {
        body_lines.push(format!("    // Rate limit: {}/{}", rl.count, rl.period));
    }

    // Return type
    let return_type = match &ep.output {
        OutputSpec::Json { schema } => format!("Result<Json<{schema}>, AppError>"),
        OutputSpec::Text => "Result<String, AppError>".to_string(),
        OutputSpec::NoContent => "Result<(), AppError>".to_string(),
    };

    // Build the response
    let response = match &ep.output {
        OutputSpec::Json { schema } => format!("    Ok(Json({schema} {{ /* TODO */ }}))", ),
        OutputSpec::Text => "    Ok(\"OK\".to_string())".to_string(),
        OutputSpec::NoContent => "    Ok(())".to_string(),
    };

    // Assemble function
    let mut out = String::new();
    // Doc comments
    if let Some(desc) = &ep.description {
        out.push_str(&format!("/// {desc}\n"));
    }
    out.push_str(&format!(
        "pub async fn {fn_name}({}) -> {return_type} {{\n",
        params.join(", ")
    ));
    for line in &body_lines {
        if !line.starts_with("///") {
            out.push_str(line);
            out.push('\n');
        }
    }
    out.push_str(&response);
    out.push('\n');
    out.push_str("}\n");

    out
}

/// Convert a URL path + method to a unique Rust function name.
/// Adds method prefix when needed to avoid collisions (e.g., GET /posts/:id + DELETE /posts/:id).
fn path_to_fn_name(path: &str) -> String {
    path.trim_start_matches('/')
        .replace('/', "_")
        .replace('-', "_")
        .replace('{', "")
        .replace('}', "")
        .replace(':', "")
}

fn unique_fn_name(ep: &ApiEndpoint, all: &[ApiEndpoint]) -> String {
    let base = path_to_fn_name(&ep.path);
    let same_path_count = all.iter().filter(|e| path_to_fn_name(&e.path) == base).count();
    if same_path_count > 1 {
        let prefix = match ep.method {
            HttpMethod::Get => "get",
            HttpMethod::Post => "create",
            HttpMethod::Put => "update",
            HttpMethod::Delete => "delete",
        };
        format!("{prefix}_{base}")
    } else {
        base
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn generate_simple_get() {
        let endpoint = ApiEndpoint {
            method: HttpMethod::Get,
            path: "/health".into(),
            input: InputSpec::None,
            output: OutputSpec::Text,
            auth: AuthRequirement::None,
            rate_limit: None,
            state: vec![],
            description: Some("Health check endpoint".into()),
        };
        let code = generate(&[endpoint]);
        assert!(code.contains("pub async fn health("));
        assert!(code.contains("Result<String, AppError>"));
        assert!(code.contains(".route(\"/health\", get(health))"));
    }

    #[test]
    fn generate_complex_post() {
        let endpoint = ApiEndpoint {
            method: HttpMethod::Post,
            path: "/users/me/avatar".into(),
            input: InputSpec::File { max_size: Some("5MB".into()), types: vec!["image/*".into()] },
            output: OutputSpec::Json { schema: "UserAvatar".into() },
            auth: AuthRequirement::Required,
            rate_limit: Some(RateLimit { count: 10, period: "min".into() }),
            state: vec![],
            description: Some("Upload user avatar".into()),
        };
        let code = generate(&[endpoint]);
        assert!(code.contains("pub async fn users_me_avatar("));
        assert!(code.contains("_auth: AuthUser"));
        assert!(code.contains("Multipart"));
        assert!(code.contains("pub struct UserAvatar"));
        assert!(code.contains("// Rate limit: 10/min"));
    }

    #[test]
    fn path_to_fn_name_works() {
        assert_eq!(path_to_fn_name("/users/me/avatar"), "users_me_avatar");
        assert_eq!(path_to_fn_name("/health"), "health");
        assert_eq!(path_to_fn_name("/api/v1/upload-file"), "api_v1_upload_file");
    }
}
